# Generated by Django 2.2.12 on 2020-05-25 22:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_auto_20200522_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='hash_url',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
