# Generated by Django 2.2.12 on 2020-05-12 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_course_abc_to_mti'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseOld',
        ),
    ]
